
package ScopeProtoJava;

import com.google.protobuf.*;
//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: PeriodicPositionProto.proto

public final class PeriodicPositionProto {
private PeriodicPositionProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
public interface PeriodicPositionOrBuilder extends
   // @@protoc_insertion_point(interface_extends:PeriodicPosition)
   com.google.protobuf.MessageOrBuilder {

 /**
  * <code>required .EventHeader header = 1;</code>
  */
 boolean hasHeader();
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 EventHeaderProto.EventHeader getHeader();
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder();

 /**
  * <code>optional uint32 rpm = 2;</code>
  *
  * <pre>
  * Engine revolutions per minute (r/min). Precision: 100
  * </pre>
  */
 boolean hasRpm();
 /**
  * <code>optional uint32 rpm = 2;</code>
  *
  * <pre>
  * Engine revolutions per minute (r/min). Precision: 100
  * </pre>
  */
 int getRpm();

 /**
  * <code>optional uint32 trip_duration_seconds = 3;</code>
  *
  * <pre>
  * Trip duration in seconds
  * </pre>
  */
 boolean hasTripDurationSeconds();
 /**
  * <code>optional uint32 trip_duration_seconds = 3;</code>
  *
  * <pre>
  * Trip duration in seconds
  * </pre>
  */
 int getTripDurationSeconds();

 /**
  * <code>optional uint32 trip_distance_meters = 4;</code>
  *
  * <pre>
  * Trip distance in meters
  * </pre>
  */
 boolean hasTripDistanceMeters();
 /**
  * <code>optional uint32 trip_distance_meters = 4;</code>
  *
  * <pre>
  * Trip distance in meters
  * </pre>
  */
 int getTripDistanceMeters();
}
/**
* Protobuf type {@code PeriodicPosition}
*
* <pre>
* Periodic Position
* </pre>
*/
public static final class PeriodicPosition extends
   com.google.protobuf.GeneratedMessage implements
   // @@protoc_insertion_point(message_implements:PeriodicPosition)
   PeriodicPositionOrBuilder {
 // Use PeriodicPosition.newBuilder() to construct.
 private PeriodicPosition(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
   super(builder);
   this.unknownFields = builder.getUnknownFields();
 }
 private PeriodicPosition(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

 private static final PeriodicPosition defaultInstance;
 public static PeriodicPosition getDefaultInstance() {
   return defaultInstance;
 }

 public PeriodicPosition getDefaultInstanceForType() {
   return defaultInstance;
 }

 private final com.google.protobuf.UnknownFieldSet unknownFields;
 @java.lang.Override
 public final com.google.protobuf.UnknownFieldSet
     getUnknownFields() {
   return this.unknownFields;
 }
 private PeriodicPosition(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   initFields();
   int mutable_bitField0_ = 0;
   com.google.protobuf.UnknownFieldSet.Builder unknownFields =
       com.google.protobuf.UnknownFieldSet.newBuilder();
   try {
     boolean done = false;
     while (!done) {
       int tag = input.readTag();
       switch (tag) {
         case 0:
           done = true;
           break;
         default: {
           if (!parseUnknownField(input, unknownFields,
                                  extensionRegistry, tag)) {
             done = true;
           }
           break;
         }
         case 10: {
           EventHeaderProto.EventHeader.Builder subBuilder = null;
           if (((bitField0_ & 0x00000001) == 0x00000001)) {
             subBuilder = header_.toBuilder();
           }
           header_ = input.readMessage(EventHeaderProto.EventHeader.PARSER, extensionRegistry);
           if (subBuilder != null) {
             subBuilder.mergeFrom(header_);
             header_ = subBuilder.buildPartial();
           }
           bitField0_ |= 0x00000001;
           break;
         }
         case 16: {
           bitField0_ |= 0x00000002;
           rpm_ = input.readUInt32();
           break;
         }
         case 24: {
           bitField0_ |= 0x00000004;
           tripDurationSeconds_ = input.readUInt32();
           break;
         }
         case 32: {
           bitField0_ |= 0x00000008;
           tripDistanceMeters_ = input.readUInt32();
           break;
         }
       }
     }
   } catch (com.google.protobuf.InvalidProtocolBufferException e) {
     throw e.setUnfinishedMessage(this);
   } catch (java.io.IOException e) {
     throw new com.google.protobuf.InvalidProtocolBufferException(
         e.getMessage()).setUnfinishedMessage(this);
   } finally {
     this.unknownFields = unknownFields.build();
     makeExtensionsImmutable();
   }
 }
 public static final com.google.protobuf.Descriptors.Descriptor
     getDescriptor() {
   return PeriodicPositionProto.internal_static_PeriodicPosition_descriptor;
 }

 protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
     internalGetFieldAccessorTable() {
   return PeriodicPositionProto.internal_static_PeriodicPosition_fieldAccessorTable
       .ensureFieldAccessorsInitialized(
           PeriodicPositionProto.PeriodicPosition.class, PeriodicPositionProto.PeriodicPosition.Builder.class);
 }

 public static com.google.protobuf.Parser<PeriodicPosition> PARSER =
     new com.google.protobuf.AbstractParser<PeriodicPosition>() {
   public PeriodicPosition parsePartialFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return new PeriodicPosition(input, extensionRegistry);
   }
 };

 @java.lang.Override
 public com.google.protobuf.Parser<PeriodicPosition> getParserForType() {
   return PARSER;
 }

 private int bitField0_;
 public static final int HEADER_FIELD_NUMBER = 1;
 private EventHeaderProto.EventHeader header_;
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public boolean hasHeader() {
   return ((bitField0_ & 0x00000001) == 0x00000001);
 }
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public EventHeaderProto.EventHeader getHeader() {
   return header_;
 }
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
   return header_;
 }

 public static final int RPM_FIELD_NUMBER = 2;
 private int rpm_;
 /**
  * <code>optional uint32 rpm = 2;</code>
  *
  * <pre>
  * Engine revolutions per minute (r/min). Precision: 100
  * </pre>
  */
 public boolean hasRpm() {
   return ((bitField0_ & 0x00000002) == 0x00000002);
 }
 /**
  * <code>optional uint32 rpm = 2;</code>
  *
  * <pre>
  * Engine revolutions per minute (r/min). Precision: 100
  * </pre>
  */
 public int getRpm() {
   return rpm_;
 }

 public static final int TRIP_DURATION_SECONDS_FIELD_NUMBER = 3;
 private int tripDurationSeconds_;
 /**
  * <code>optional uint32 trip_duration_seconds = 3;</code>
  *
  * <pre>
  * Trip duration in seconds
  * </pre>
  */
 public boolean hasTripDurationSeconds() {
   return ((bitField0_ & 0x00000004) == 0x00000004);
 }
 /**
  * <code>optional uint32 trip_duration_seconds = 3;</code>
  *
  * <pre>
  * Trip duration in seconds
  * </pre>
  */
 public int getTripDurationSeconds() {
   return tripDurationSeconds_;
 }

 public static final int TRIP_DISTANCE_METERS_FIELD_NUMBER = 4;
 private int tripDistanceMeters_;
 /**
  * <code>optional uint32 trip_distance_meters = 4;</code>
  *
  * <pre>
  * Trip distance in meters
  * </pre>
  */
 public boolean hasTripDistanceMeters() {
   return ((bitField0_ & 0x00000008) == 0x00000008);
 }
 /**
  * <code>optional uint32 trip_distance_meters = 4;</code>
  *
  * <pre>
  * Trip distance in meters
  * </pre>
  */
 public int getTripDistanceMeters() {
   return tripDistanceMeters_;
 }

 private void initFields() {
   header_ = EventHeaderProto.EventHeader.getDefaultInstance();
   rpm_ = 0;
   tripDurationSeconds_ = 0;
   tripDistanceMeters_ = 0;
 }
 private byte memoizedIsInitialized = -1;
 public final boolean isInitialized() {
   byte isInitialized = memoizedIsInitialized;
   if (isInitialized == 1) return true;
   if (isInitialized == 0) return false;

   if (!hasHeader()) {
     memoizedIsInitialized = 0;
     return false;
   }
   if (!getHeader().isInitialized()) {
     memoizedIsInitialized = 0;
     return false;
   }
   memoizedIsInitialized = 1;
   return true;
 }

 public void writeTo(com.google.protobuf.CodedOutputStream output)
                     throws java.io.IOException {
   getSerializedSize();
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     output.writeMessage(1, header_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     output.writeUInt32(2, rpm_);
   }
   if (((bitField0_ & 0x00000004) == 0x00000004)) {
     output.writeUInt32(3, tripDurationSeconds_);
   }
   if (((bitField0_ & 0x00000008) == 0x00000008)) {
     output.writeUInt32(4, tripDistanceMeters_);
   }
   getUnknownFields().writeTo(output);
 }

 private int memoizedSerializedSize = -1;
 public int getSerializedSize() {
   int size = memoizedSerializedSize;
   if (size != -1) return size;

   size = 0;
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     size += com.google.protobuf.CodedOutputStream
       .computeMessageSize(1, header_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(2, rpm_);
   }
   if (((bitField0_ & 0x00000004) == 0x00000004)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(3, tripDurationSeconds_);
   }
   if (((bitField0_ & 0x00000008) == 0x00000008)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(4, tripDistanceMeters_);
   }
   size += getUnknownFields().getSerializedSize();
   memoizedSerializedSize = size;
   return size;
 }

 private static final long serialVersionUID = 0L;
 @java.lang.Override
 protected java.lang.Object writeReplace()
     throws java.io.ObjectStreamException {
   return super.writeReplace();
 }

 public static PeriodicPositionProto.PeriodicPosition parseFrom(
     com.google.protobuf.ByteString data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static PeriodicPositionProto.PeriodicPosition parseFrom(
     com.google.protobuf.ByteString data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static PeriodicPositionProto.PeriodicPosition parseFrom(byte[] data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static PeriodicPositionProto.PeriodicPosition parseFrom(
     byte[] data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static PeriodicPositionProto.PeriodicPosition parseFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static PeriodicPositionProto.PeriodicPosition parseFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }
 public static PeriodicPositionProto.PeriodicPosition parseDelimitedFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input);
 }
 public static PeriodicPositionProto.PeriodicPosition parseDelimitedFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input, extensionRegistry);
 }
 public static PeriodicPositionProto.PeriodicPosition parseFrom(
     com.google.protobuf.CodedInputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static PeriodicPositionProto.PeriodicPosition parseFrom(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }

 public static Builder newBuilder() { return Builder.create(); }
 public Builder newBuilderForType() { return newBuilder(); }
 public static Builder newBuilder(PeriodicPositionProto.PeriodicPosition prototype) {
   return newBuilder().mergeFrom(prototype);
 }
 public Builder toBuilder() { return newBuilder(this); }

 @java.lang.Override
 protected Builder newBuilderForType(
     com.google.protobuf.GeneratedMessage.BuilderParent parent) {
   Builder builder = new Builder(parent);
   return builder;
 }
 /**
  * Protobuf type {@code PeriodicPosition}
  *
  * <pre>
  * Periodic Position
  * </pre>
  */
 public static final class Builder extends
     com.google.protobuf.GeneratedMessage.Builder<Builder> implements
     // @@protoc_insertion_point(builder_implements:PeriodicPosition)
     PeriodicPositionProto.PeriodicPositionOrBuilder {
   public static final com.google.protobuf.Descriptors.Descriptor
       getDescriptor() {
     return PeriodicPositionProto.internal_static_PeriodicPosition_descriptor;
   }

   protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
       internalGetFieldAccessorTable() {
     return PeriodicPositionProto.internal_static_PeriodicPosition_fieldAccessorTable
         .ensureFieldAccessorsInitialized(
             PeriodicPositionProto.PeriodicPosition.class, PeriodicPositionProto.PeriodicPosition.Builder.class);
   }

   // Construct using PeriodicPositionProto.PeriodicPosition.newBuilder()
   private Builder() {
     maybeForceBuilderInitialization();
   }

   private Builder(
       com.google.protobuf.GeneratedMessage.BuilderParent parent) {
     super(parent);
     maybeForceBuilderInitialization();
   }
   private void maybeForceBuilderInitialization() {
     if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
       getHeaderFieldBuilder();
     }
   }
   private static Builder create() {
     return new Builder();
   }

   public Builder clear() {
     super.clear();
     if (headerBuilder_ == null) {
       header_ = EventHeaderProto.EventHeader.getDefaultInstance();
     } else {
       headerBuilder_.clear();
     }
     bitField0_ = (bitField0_ & ~0x00000001);
     rpm_ = 0;
     bitField0_ = (bitField0_ & ~0x00000002);
     tripDurationSeconds_ = 0;
     bitField0_ = (bitField0_ & ~0x00000004);
     tripDistanceMeters_ = 0;
     bitField0_ = (bitField0_ & ~0x00000008);
     return this;
   }

   public Builder clone() {
     return create().mergeFrom(buildPartial());
   }

   public com.google.protobuf.Descriptors.Descriptor
       getDescriptorForType() {
     return PeriodicPositionProto.internal_static_PeriodicPosition_descriptor;
   }

   public PeriodicPositionProto.PeriodicPosition getDefaultInstanceForType() {
     return PeriodicPositionProto.PeriodicPosition.getDefaultInstance();
   }

   public PeriodicPositionProto.PeriodicPosition build() {
     PeriodicPosition result = buildPartial();
     if (!result.isInitialized()) {
       throw newUninitializedMessageException(result);
     }
     return result;
   }

   public PeriodicPositionProto.PeriodicPosition buildPartial() {
     PeriodicPositionProto.PeriodicPosition result = new PeriodicPositionProto.PeriodicPosition(this);
     int from_bitField0_ = bitField0_;
     int to_bitField0_ = 0;
     if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
       to_bitField0_ |= 0x00000001;
     }
     if (headerBuilder_ == null) {
       result.header_ = header_;
     } else {
       result.header_ = headerBuilder_.build();
     }
     if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
       to_bitField0_ |= 0x00000002;
     }
     result.rpm_ = rpm_;
     if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
       to_bitField0_ |= 0x00000004;
     }
     result.tripDurationSeconds_ = tripDurationSeconds_;
     if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
       to_bitField0_ |= 0x00000008;
     }
     result.tripDistanceMeters_ = tripDistanceMeters_;
     result.bitField0_ = to_bitField0_;
     onBuilt();
     return result;
   }

   public Builder mergeFrom(com.google.protobuf.Message other) {
     if (other instanceof PeriodicPositionProto.PeriodicPosition) {
       return mergeFrom((PeriodicPositionProto.PeriodicPosition)other);
     } else {
       super.mergeFrom(other);
       return this;
     }
   }

   public Builder mergeFrom(PeriodicPositionProto.PeriodicPosition other) {
     if (other == PeriodicPositionProto.PeriodicPosition.getDefaultInstance()) return this;
     if (other.hasHeader()) {
       mergeHeader(other.getHeader());
     }
     if (other.hasRpm()) {
       setRpm(other.getRpm());
     }
     if (other.hasTripDurationSeconds()) {
       setTripDurationSeconds(other.getTripDurationSeconds());
     }
     if (other.hasTripDistanceMeters()) {
       setTripDistanceMeters(other.getTripDistanceMeters());
     }
     this.mergeUnknownFields(other.getUnknownFields());
     return this;
   }

   public final boolean isInitialized() {
     if (!hasHeader()) {
       
       return false;
     }
     if (!getHeader().isInitialized()) {
       
       return false;
     }
     return true;
   }

   public Builder mergeFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     PeriodicPositionProto.PeriodicPosition parsedMessage = null;
     try {
       parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
     } catch (com.google.protobuf.InvalidProtocolBufferException e) {
       parsedMessage = (PeriodicPositionProto.PeriodicPosition) e.getUnfinishedMessage();
       throw e;
     } finally {
       if (parsedMessage != null) {
         mergeFrom(parsedMessage);
       }
     }
     return this;
   }
   private int bitField0_;

   private EventHeaderProto.EventHeader header_ = EventHeaderProto.EventHeader.getDefaultInstance();
   private com.google.protobuf.SingleFieldBuilder<
       EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder> headerBuilder_;
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public boolean hasHeader() {
     return ((bitField0_ & 0x00000001) == 0x00000001);
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeader getHeader() {
     if (headerBuilder_ == null) {
       return header_;
     } else {
       return headerBuilder_.getMessage();
     }
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder setHeader(EventHeaderProto.EventHeader value) {
     if (headerBuilder_ == null) {
       if (value == null) {
         throw new NullPointerException();
       }
       header_ = value;
       onChanged();
     } else {
       headerBuilder_.setMessage(value);
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder setHeader(
       EventHeaderProto.EventHeader.Builder builderForValue) {
     if (headerBuilder_ == null) {
       header_ = builderForValue.build();
       onChanged();
     } else {
       headerBuilder_.setMessage(builderForValue.build());
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder mergeHeader(EventHeaderProto.EventHeader value) {
     if (headerBuilder_ == null) {
       if (((bitField0_ & 0x00000001) == 0x00000001) &&
           header_ != EventHeaderProto.EventHeader.getDefaultInstance()) {
         header_ =
           EventHeaderProto.EventHeader.newBuilder(header_).mergeFrom(value).buildPartial();
       } else {
         header_ = value;
       }
       onChanged();
     } else {
       headerBuilder_.mergeFrom(value);
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder clearHeader() {
     if (headerBuilder_ == null) {
       header_ = EventHeaderProto.EventHeader.getDefaultInstance();
       onChanged();
     } else {
       headerBuilder_.clear();
     }
     bitField0_ = (bitField0_ & ~0x00000001);
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeader.Builder getHeaderBuilder() {
     bitField0_ |= 0x00000001;
     onChanged();
     return getHeaderFieldBuilder().getBuilder();
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
     if (headerBuilder_ != null) {
       return headerBuilder_.getMessageOrBuilder();
     } else {
       return header_;
     }
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   private com.google.protobuf.SingleFieldBuilder<
       EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder> 
       getHeaderFieldBuilder() {
     if (headerBuilder_ == null) {
       headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
           EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder>(
               getHeader(),
               getParentForChildren(),
               isClean());
       header_ = null;
     }
     return headerBuilder_;
   }

   private int rpm_ ;
   /**
    * <code>optional uint32 rpm = 2;</code>
    *
    * <pre>
    * Engine revolutions per minute (r/min). Precision: 100
    * </pre>
    */
   public boolean hasRpm() {
     return ((bitField0_ & 0x00000002) == 0x00000002);
   }
   /**
    * <code>optional uint32 rpm = 2;</code>
    *
    * <pre>
    * Engine revolutions per minute (r/min). Precision: 100
    * </pre>
    */
   public int getRpm() {
     return rpm_;
   }
   /**
    * <code>optional uint32 rpm = 2;</code>
    *
    * <pre>
    * Engine revolutions per minute (r/min). Precision: 100
    * </pre>
    */
   public Builder setRpm(int value) {
     bitField0_ |= 0x00000002;
     rpm_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 rpm = 2;</code>
    *
    * <pre>
    * Engine revolutions per minute (r/min). Precision: 100
    * </pre>
    */
   public Builder clearRpm() {
     bitField0_ = (bitField0_ & ~0x00000002);
     rpm_ = 0;
     onChanged();
     return this;
   }

   private int tripDurationSeconds_ ;
   /**
    * <code>optional uint32 trip_duration_seconds = 3;</code>
    *
    * <pre>
    * Trip duration in seconds
    * </pre>
    */
   public boolean hasTripDurationSeconds() {
     return ((bitField0_ & 0x00000004) == 0x00000004);
   }
   /**
    * <code>optional uint32 trip_duration_seconds = 3;</code>
    *
    * <pre>
    * Trip duration in seconds
    * </pre>
    */
   public int getTripDurationSeconds() {
     return tripDurationSeconds_;
   }
   /**
    * <code>optional uint32 trip_duration_seconds = 3;</code>
    *
    * <pre>
    * Trip duration in seconds
    * </pre>
    */
   public Builder setTripDurationSeconds(int value) {
     bitField0_ |= 0x00000004;
     tripDurationSeconds_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 trip_duration_seconds = 3;</code>
    *
    * <pre>
    * Trip duration in seconds
    * </pre>
    */
   public Builder clearTripDurationSeconds() {
     bitField0_ = (bitField0_ & ~0x00000004);
     tripDurationSeconds_ = 0;
     onChanged();
     return this;
   }

   private int tripDistanceMeters_ ;
   /**
    * <code>optional uint32 trip_distance_meters = 4;</code>
    *
    * <pre>
    * Trip distance in meters
    * </pre>
    */
   public boolean hasTripDistanceMeters() {
     return ((bitField0_ & 0x00000008) == 0x00000008);
   }
   /**
    * <code>optional uint32 trip_distance_meters = 4;</code>
    *
    * <pre>
    * Trip distance in meters
    * </pre>
    */
   public int getTripDistanceMeters() {
     return tripDistanceMeters_;
   }
   /**
    * <code>optional uint32 trip_distance_meters = 4;</code>
    *
    * <pre>
    * Trip distance in meters
    * </pre>
    */
   public Builder setTripDistanceMeters(int value) {
     bitField0_ |= 0x00000008;
     tripDistanceMeters_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 trip_distance_meters = 4;</code>
    *
    * <pre>
    * Trip distance in meters
    * </pre>
    */
   public Builder clearTripDistanceMeters() {
     bitField0_ = (bitField0_ & ~0x00000008);
     tripDistanceMeters_ = 0;
     onChanged();
     return this;
   }

   // @@protoc_insertion_point(builder_scope:PeriodicPosition)
 }

 static {
   defaultInstance = new PeriodicPosition(true);
   defaultInstance.initFields();
 }

 // @@protoc_insertion_point(class_scope:PeriodicPosition)
}

private static final com.google.protobuf.Descriptors.Descriptor
 internal_static_PeriodicPosition_descriptor;
private static
 com.google.protobuf.GeneratedMessage.FieldAccessorTable
   internal_static_PeriodicPosition_fieldAccessorTable;

public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\033PeriodicPositionProto.proto\032\026EventHead" +
   "erProto.proto\"z\n\020PeriodicPosition\022\034\n\006hea" +
   "der\030\001 \002(\0132\014.EventHeader\022\013\n\003rpm\030\002 \001(\r\022\035\n\025" +
   "trip_duration_seconds\030\003 \001(\r\022\034\n\024trip_dist" +
   "ance_meters\030\004 \001(\r"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
       EventHeaderProto.getDescriptor(),
     }, assigner);
 internal_static_PeriodicPosition_descriptor =
   getDescriptor().getMessageTypes().get(0);
 internal_static_PeriodicPosition_fieldAccessorTable = new
   com.google.protobuf.GeneratedMessage.FieldAccessorTable(
     internal_static_PeriodicPosition_descriptor,
     new java.lang.String[] { "Header", "Rpm", "TripDurationSeconds", "TripDistanceMeters", });
 EventHeaderProto.getDescriptor();
}

// @@protoc_insertion_point(outer_class_scope)
}

