package scopeProto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: ExcessiveIdleProto.proto

public final class ExcessiveIdleProto {
private ExcessiveIdleProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
public interface ExcessiveIdleOrBuilder extends
   // @@protoc_insertion_point(interface_extends:ExcessiveIdle)
   com.google.protobuf.MessageOrBuilder {

 /**
  * <code>required .EventHeader header = 1;</code>
  */
 boolean hasHeader();
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 EventHeaderProto.EventHeader getHeader();
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder();

 /**
  * <code>optional uint32 rpm = 2;</code>
  *
  * <pre>
  * RPM
  * </pre>
  */
 boolean hasRpm();
 /**
  * <code>optional uint32 rpm = 2;</code>
  *
  * <pre>
  * RPM
  * </pre>
  */
 int getRpm();

 /**
  * <code>optional uint32 duration_seconds = 3;</code>
  *
  * <pre>
  * Duration in seconds
  * </pre>
  */
 boolean hasDurationSeconds();
 /**
  * <code>optional uint32 duration_seconds = 3;</code>
  *
  * <pre>
  * Duration in seconds
  * </pre>
  */
 int getDurationSeconds();
}
/**
* Protobuf type {@code ExcessiveIdle}
*
* <pre>
* Excessive Idle
* </pre>
*/
public static final class ExcessiveIdle extends
   com.google.protobuf.GeneratedMessage implements
   // @@protoc_insertion_point(message_implements:ExcessiveIdle)
   ExcessiveIdleOrBuilder {
 // Use ExcessiveIdle.newBuilder() to construct.
 private ExcessiveIdle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
   super(builder);
   this.unknownFields = builder.getUnknownFields();
 }
 private ExcessiveIdle(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

 private static final ExcessiveIdle defaultInstance;
 public static ExcessiveIdle getDefaultInstance() {
   return defaultInstance;
 }

 public ExcessiveIdle getDefaultInstanceForType() {
   return defaultInstance;
 }

 private final com.google.protobuf.UnknownFieldSet unknownFields;
 @java.lang.Override
 public final com.google.protobuf.UnknownFieldSet
     getUnknownFields() {
   return this.unknownFields;
 }
 private ExcessiveIdle(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   initFields();
   int mutable_bitField0_ = 0;
   com.google.protobuf.UnknownFieldSet.Builder unknownFields =
       com.google.protobuf.UnknownFieldSet.newBuilder();
   try {
     boolean done = false;
     while (!done) {
       int tag = input.readTag();
       switch (tag) {
         case 0:
           done = true;
           break;
         default: {
           if (!parseUnknownField(input, unknownFields,
                                  extensionRegistry, tag)) {
             done = true;
           }
           break;
         }
         case 10: {
           EventHeaderProto.EventHeader.Builder subBuilder = null;
           if (((bitField0_ & 0x00000001) == 0x00000001)) {
             subBuilder = header_.toBuilder();
           }
           header_ = input.readMessage(EventHeaderProto.EventHeader.PARSER, extensionRegistry);
           if (subBuilder != null) {
             subBuilder.mergeFrom(header_);
             header_ = subBuilder.buildPartial();
           }
           bitField0_ |= 0x00000001;
           break;
         }
         case 16: {
           bitField0_ |= 0x00000002;
           rpm_ = input.readUInt32();
           break;
         }
         case 24: {
           bitField0_ |= 0x00000004;
           durationSeconds_ = input.readUInt32();
           break;
         }
       }
     }
   } catch (com.google.protobuf.InvalidProtocolBufferException e) {
     throw e.setUnfinishedMessage(this);
   } catch (java.io.IOException e) {
     throw new com.google.protobuf.InvalidProtocolBufferException(
         e.getMessage()).setUnfinishedMessage(this);
   } finally {
     this.unknownFields = unknownFields.build();
     makeExtensionsImmutable();
   }
 }
 public static final com.google.protobuf.Descriptors.Descriptor
     getDescriptor() {
   return ExcessiveIdleProto.internal_static_ExcessiveIdle_descriptor;
 }

 protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
     internalGetFieldAccessorTable() {
   return ExcessiveIdleProto.internal_static_ExcessiveIdle_fieldAccessorTable
       .ensureFieldAccessorsInitialized(
           ExcessiveIdleProto.ExcessiveIdle.class, ExcessiveIdleProto.ExcessiveIdle.Builder.class);
 }

 public static com.google.protobuf.Parser<ExcessiveIdle> PARSER =
     new com.google.protobuf.AbstractParser<ExcessiveIdle>() {
   public ExcessiveIdle parsePartialFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return new ExcessiveIdle(input, extensionRegistry);
   }
 };

 @java.lang.Override
 public com.google.protobuf.Parser<ExcessiveIdle> getParserForType() {
   return PARSER;
 }

 private int bitField0_;
 public static final int HEADER_FIELD_NUMBER = 1;
 private EventHeaderProto.EventHeader header_;
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public boolean hasHeader() {
   return ((bitField0_ & 0x00000001) == 0x00000001);
 }
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public EventHeaderProto.EventHeader getHeader() {
   return header_;
 }
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
   return header_;
 }

 public static final int RPM_FIELD_NUMBER = 2;
 private int rpm_;
 /**
  * <code>optional uint32 rpm = 2;</code>
  *
  * <pre>
  * RPM
  * </pre>
  */
 public boolean hasRpm() {
   return ((bitField0_ & 0x00000002) == 0x00000002);
 }
 /**
  * <code>optional uint32 rpm = 2;</code>
  *
  * <pre>
  * RPM
  * </pre>
  */
 public int getRpm() {
   return rpm_;
 }

 public static final int DURATION_SECONDS_FIELD_NUMBER = 3;
 private int durationSeconds_;
 /**
  * <code>optional uint32 duration_seconds = 3;</code>
  *
  * <pre>
  * Duration in seconds
  * </pre>
  */
 public boolean hasDurationSeconds() {
   return ((bitField0_ & 0x00000004) == 0x00000004);
 }
 /**
  * <code>optional uint32 duration_seconds = 3;</code>
  *
  * <pre>
  * Duration in seconds
  * </pre>
  */
 public int getDurationSeconds() {
   return durationSeconds_;
 }

 private void initFields() {
   header_ = EventHeaderProto.EventHeader.getDefaultInstance();
   rpm_ = 0;
   durationSeconds_ = 0;
 }
 private byte memoizedIsInitialized = -1;
 public final boolean isInitialized() {
   byte isInitialized = memoizedIsInitialized;
   if (isInitialized == 1) return true;
   if (isInitialized == 0) return false;

   if (!hasHeader()) {
     memoizedIsInitialized = 0;
     return false;
   }
   if (!getHeader().isInitialized()) {
     memoizedIsInitialized = 0;
     return false;
   }
   memoizedIsInitialized = 1;
   return true;
 }

 public void writeTo(com.google.protobuf.CodedOutputStream output)
                     throws java.io.IOException {
   getSerializedSize();
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     output.writeMessage(1, header_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     output.writeUInt32(2, rpm_);
   }
   if (((bitField0_ & 0x00000004) == 0x00000004)) {
     output.writeUInt32(3, durationSeconds_);
   }
   getUnknownFields().writeTo(output);
 }

 private int memoizedSerializedSize = -1;
 public int getSerializedSize() {
   int size = memoizedSerializedSize;
   if (size != -1) return size;

   size = 0;
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     size += com.google.protobuf.CodedOutputStream
       .computeMessageSize(1, header_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(2, rpm_);
   }
   if (((bitField0_ & 0x00000004) == 0x00000004)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(3, durationSeconds_);
   }
   size += getUnknownFields().getSerializedSize();
   memoizedSerializedSize = size;
   return size;
 }

 private static final long serialVersionUID = 0L;
 @java.lang.Override
 protected java.lang.Object writeReplace()
     throws java.io.ObjectStreamException {
   return super.writeReplace();
 }

 public static ExcessiveIdleProto.ExcessiveIdle parseFrom(
     com.google.protobuf.ByteString data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static ExcessiveIdleProto.ExcessiveIdle parseFrom(
     com.google.protobuf.ByteString data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static ExcessiveIdleProto.ExcessiveIdle parseFrom(byte[] data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static ExcessiveIdleProto.ExcessiveIdle parseFrom(
     byte[] data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static ExcessiveIdleProto.ExcessiveIdle parseFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static ExcessiveIdleProto.ExcessiveIdle parseFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }
 public static ExcessiveIdleProto.ExcessiveIdle parseDelimitedFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input);
 }
 public static ExcessiveIdleProto.ExcessiveIdle parseDelimitedFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input, extensionRegistry);
 }
 public static ExcessiveIdleProto.ExcessiveIdle parseFrom(
     com.google.protobuf.CodedInputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static ExcessiveIdleProto.ExcessiveIdle parseFrom(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }

 public static Builder newBuilder() { return Builder.create(); }
 public Builder newBuilderForType() { return newBuilder(); }
 public static Builder newBuilder(ExcessiveIdleProto.ExcessiveIdle prototype) {
   return newBuilder().mergeFrom(prototype);
 }
 public Builder toBuilder() { return newBuilder(this); }

 @java.lang.Override
 protected Builder newBuilderForType(
     com.google.protobuf.GeneratedMessage.BuilderParent parent) {
   Builder builder = new Builder(parent);
   return builder;
 }
 /**
  * Protobuf type {@code ExcessiveIdle}
  *
  * <pre>
  * Excessive Idle
  * </pre>
  */
 public static final class Builder extends
     com.google.protobuf.GeneratedMessage.Builder<Builder> implements
     // @@protoc_insertion_point(builder_implements:ExcessiveIdle)
     ExcessiveIdleProto.ExcessiveIdleOrBuilder {
   public static final com.google.protobuf.Descriptors.Descriptor
       getDescriptor() {
     return ExcessiveIdleProto.internal_static_ExcessiveIdle_descriptor;
   }

   protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
       internalGetFieldAccessorTable() {
     return ExcessiveIdleProto.internal_static_ExcessiveIdle_fieldAccessorTable
         .ensureFieldAccessorsInitialized(
             ExcessiveIdleProto.ExcessiveIdle.class, ExcessiveIdleProto.ExcessiveIdle.Builder.class);
   }

   // Construct using ExcessiveIdleProto.ExcessiveIdle.newBuilder()
   private Builder() {
     maybeForceBuilderInitialization();
   }

   private Builder(
       com.google.protobuf.GeneratedMessage.BuilderParent parent) {
     super(parent);
     maybeForceBuilderInitialization();
   }
   private void maybeForceBuilderInitialization() {
     if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
       getHeaderFieldBuilder();
     }
   }
   private static Builder create() {
     return new Builder();
   }

   public Builder clear() {
     super.clear();
     if (headerBuilder_ == null) {
       header_ = EventHeaderProto.EventHeader.getDefaultInstance();
     } else {
       headerBuilder_.clear();
     }
     bitField0_ = (bitField0_ & ~0x00000001);
     rpm_ = 0;
     bitField0_ = (bitField0_ & ~0x00000002);
     durationSeconds_ = 0;
     bitField0_ = (bitField0_ & ~0x00000004);
     return this;
   }

   public Builder clone() {
     return create().mergeFrom(buildPartial());
   }

   public com.google.protobuf.Descriptors.Descriptor
       getDescriptorForType() {
     return ExcessiveIdleProto.internal_static_ExcessiveIdle_descriptor;
   }

   public ExcessiveIdleProto.ExcessiveIdle getDefaultInstanceForType() {
     return ExcessiveIdleProto.ExcessiveIdle.getDefaultInstance();
   }

   public ExcessiveIdleProto.ExcessiveIdle build() {
     ExcessiveIdleProto.ExcessiveIdle result = buildPartial();
     if (!result.isInitialized()) {
       throw newUninitializedMessageException(result);
     }
     return result;
   }

   public ExcessiveIdleProto.ExcessiveIdle buildPartial() {
     ExcessiveIdleProto.ExcessiveIdle result = new ExcessiveIdleProto.ExcessiveIdle(this);
     int from_bitField0_ = bitField0_;
     int to_bitField0_ = 0;
     if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
       to_bitField0_ |= 0x00000001;
     }
     if (headerBuilder_ == null) {
       result.header_ = header_;
     } else {
       result.header_ = headerBuilder_.build();
     }
     if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
       to_bitField0_ |= 0x00000002;
     }
     result.rpm_ = rpm_;
     if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
       to_bitField0_ |= 0x00000004;
     }
     result.durationSeconds_ = durationSeconds_;
     result.bitField0_ = to_bitField0_;
     onBuilt();
     return result;
   }

   public Builder mergeFrom(com.google.protobuf.Message other) {
     if (other instanceof ExcessiveIdleProto.ExcessiveIdle) {
       return mergeFrom((ExcessiveIdleProto.ExcessiveIdle)other);
     } else {
       super.mergeFrom(other);
       return this;
     }
   }

   public Builder mergeFrom(ExcessiveIdleProto.ExcessiveIdle other) {
     if (other == ExcessiveIdleProto.ExcessiveIdle.getDefaultInstance()) return this;
     if (other.hasHeader()) {
       mergeHeader(other.getHeader());
     }
     if (other.hasRpm()) {
       setRpm(other.getRpm());
     }
     if (other.hasDurationSeconds()) {
       setDurationSeconds(other.getDurationSeconds());
     }
     this.mergeUnknownFields(other.getUnknownFields());
     return this;
   }

   public final boolean isInitialized() {
     if (!hasHeader()) {
       
       return false;
     }
     if (!getHeader().isInitialized()) {
       
       return false;
     }
     return true;
   }

   public Builder mergeFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     ExcessiveIdleProto.ExcessiveIdle parsedMessage = null;
     try {
       parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
     } catch (com.google.protobuf.InvalidProtocolBufferException e) {
       parsedMessage = (ExcessiveIdleProto.ExcessiveIdle) e.getUnfinishedMessage();
       throw e;
     } finally {
       if (parsedMessage != null) {
         mergeFrom(parsedMessage);
       }
     }
     return this;
   }
   private int bitField0_;

   private EventHeaderProto.EventHeader header_ = EventHeaderProto.EventHeader.getDefaultInstance();
   private com.google.protobuf.SingleFieldBuilder<
       EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder> headerBuilder_;
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public boolean hasHeader() {
     return ((bitField0_ & 0x00000001) == 0x00000001);
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeader getHeader() {
     if (headerBuilder_ == null) {
       return header_;
     } else {
       return headerBuilder_.getMessage();
     }
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder setHeader(EventHeaderProto.EventHeader value) {
     if (headerBuilder_ == null) {
       if (value == null) {
         throw new NullPointerException();
       }
       header_ = value;
       onChanged();
     } else {
       headerBuilder_.setMessage(value);
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder setHeader(
       EventHeaderProto.EventHeader.Builder builderForValue) {
     if (headerBuilder_ == null) {
       header_ = builderForValue.build();
       onChanged();
     } else {
       headerBuilder_.setMessage(builderForValue.build());
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder mergeHeader(EventHeaderProto.EventHeader value) {
     if (headerBuilder_ == null) {
       if (((bitField0_ & 0x00000001) == 0x00000001) &&
           header_ != EventHeaderProto.EventHeader.getDefaultInstance()) {
         header_ =
           EventHeaderProto.EventHeader.newBuilder(header_).mergeFrom(value).buildPartial();
       } else {
         header_ = value;
       }
       onChanged();
     } else {
       headerBuilder_.mergeFrom(value);
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder clearHeader() {
     if (headerBuilder_ == null) {
       header_ = EventHeaderProto.EventHeader.getDefaultInstance();
       onChanged();
     } else {
       headerBuilder_.clear();
     }
     bitField0_ = (bitField0_ & ~0x00000001);
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeader.Builder getHeaderBuilder() {
     bitField0_ |= 0x00000001;
     onChanged();
     return getHeaderFieldBuilder().getBuilder();
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
     if (headerBuilder_ != null) {
       return headerBuilder_.getMessageOrBuilder();
     } else {
       return header_;
     }
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   private com.google.protobuf.SingleFieldBuilder<
       EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder> 
       getHeaderFieldBuilder() {
     if (headerBuilder_ == null) {
       headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
           EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder>(
               getHeader(),
               getParentForChildren(),
               isClean());
       header_ = null;
     }
     return headerBuilder_;
   }

   private int rpm_ ;
   /**
    * <code>optional uint32 rpm = 2;</code>
    *
    * <pre>
    * RPM
    * </pre>
    */
   public boolean hasRpm() {
     return ((bitField0_ & 0x00000002) == 0x00000002);
   }
   /**
    * <code>optional uint32 rpm = 2;</code>
    *
    * <pre>
    * RPM
    * </pre>
    */
   public int getRpm() {
     return rpm_;
   }
   /**
    * <code>optional uint32 rpm = 2;</code>
    *
    * <pre>
    * RPM
    * </pre>
    */
   public Builder setRpm(int value) {
     bitField0_ |= 0x00000002;
     rpm_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 rpm = 2;</code>
    *
    * <pre>
    * RPM
    * </pre>
    */
   public Builder clearRpm() {
     bitField0_ = (bitField0_ & ~0x00000002);
     rpm_ = 0;
     onChanged();
     return this;
   }

   private int durationSeconds_ ;
   /**
    * <code>optional uint32 duration_seconds = 3;</code>
    *
    * <pre>
    * Duration in seconds
    * </pre>
    */
   public boolean hasDurationSeconds() {
     return ((bitField0_ & 0x00000004) == 0x00000004);
   }
   /**
    * <code>optional uint32 duration_seconds = 3;</code>
    *
    * <pre>
    * Duration in seconds
    * </pre>
    */
   public int getDurationSeconds() {
     return durationSeconds_;
   }
   /**
    * <code>optional uint32 duration_seconds = 3;</code>
    *
    * <pre>
    * Duration in seconds
    * </pre>
    */
   public Builder setDurationSeconds(int value) {
     bitField0_ |= 0x00000004;
     durationSeconds_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 duration_seconds = 3;</code>
    *
    * <pre>
    * Duration in seconds
    * </pre>
    */
   public Builder clearDurationSeconds() {
     bitField0_ = (bitField0_ & ~0x00000004);
     durationSeconds_ = 0;
     onChanged();
     return this;
   }

   // @@protoc_insertion_point(builder_scope:ExcessiveIdle)
 }

 static {
   defaultInstance = new ExcessiveIdle(true);
   defaultInstance.initFields();
 }

 // @@protoc_insertion_point(class_scope:ExcessiveIdle)
}

private static final com.google.protobuf.Descriptors.Descriptor
 internal_static_ExcessiveIdle_descriptor;
private static
 com.google.protobuf.GeneratedMessage.FieldAccessorTable
   internal_static_ExcessiveIdle_fieldAccessorTable;

public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\030ExcessiveIdleProto.proto\032\026EventHeaderP" +
   "roto.proto\"T\n\rExcessiveIdle\022\034\n\006header\030\001 " +
   "\002(\0132\014.EventHeader\022\013\n\003rpm\030\002 \001(\r\022\030\n\020durati" +
   "on_seconds\030\003 \001(\r"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
       EventHeaderProto.getDescriptor(),
     }, assigner);
 internal_static_ExcessiveIdle_descriptor =
   getDescriptor().getMessageTypes().get(0);
 internal_static_ExcessiveIdle_fieldAccessorTable = new
   com.google.protobuf.GeneratedMessage.FieldAccessorTable(
     internal_static_ExcessiveIdle_descriptor,
     new java.lang.String[] { "Header", "Rpm", "DurationSeconds", });
 EventHeaderProto.getDescriptor();
}

// @@protoc_insertion_point(outer_class_scope)
}
