package scopeProto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: GeneralStatusTypeProto.proto

public final class GeneralStatusTypeProto {
private GeneralStatusTypeProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
/**
* Protobuf enum {@code GeneralStatusType}
*
* <pre>
* [Flags] General status
* </pre>
*/
public enum GeneralStatusType
   implements com.google.protobuf.ProtocolMessageEnum {
 /**
  * <code>GENERAL_STATUS_IGNITION = 1;</code>
  *
  * <pre>
  * Indicates that the ignition is on
  * </pre>
  */
 GENERAL_STATUS_IGNITION(0, 1),
 /**
  * <code>GENERAL_STATUS_BATTERY = 2;</code>
  *
  * <pre>
  * The unit is running on battery power
  * </pre>
  */
 GENERAL_STATUS_BATTERY(1, 2),
 /**
  * <code>GENERAL_STATUS_GPS_INFORMATION_AVAILABLE = 4;</code>
  *
  * <pre>
  * GPS information available
  * </pre>
  */
 GENERAL_STATUS_GPS_INFORMATION_AVAILABLE(2, 4),
 /**
  * <code>GENERAL_STATUS_INPUT_OUTPUT_INFORMATION_AVAILABLE = 8;</code>
  *
  * <pre>
  * Input and output information available
  * </pre>
  */
 GENERAL_STATUS_INPUT_OUTPUT_INFORMATION_AVAILABLE(3, 8),
 /**
  * <code>GENERAL_STATUS_GPS_POSITION_INVALID = 16;</code>
  *
  * <pre>
  * Specifies that the provided latitude/longitude and other GPS data was valid some time ago but is invalid now
  * </pre>
  */
 GENERAL_STATUS_GPS_POSITION_INVALID(4, 16),
 /**
  * <code>GENERAL_STATUS_GPS_STATUS_VALID = 32;</code>
  *
  * <pre>
  * Specifies that GPS is in valid status
  * </pre>
  */
 GENERAL_STATUS_GPS_STATUS_VALID(5, 32),
 /**
  * <code>GENERAL_STATUS_GPS_ANTENNA_CONNECTED = 64;</code>
  *
  * <pre>
  * Specifies that GPS antenna is connected
  * </pre>
  */
 GENERAL_STATUS_GPS_ANTENNA_CONNECTED(6, 64),
 ;

 /**
  * <code>GENERAL_STATUS_IGNITION = 1;</code>
  *
  * <pre>
  * Indicates that the ignition is on
  * </pre>
  */
 public static final int GENERAL_STATUS_IGNITION_VALUE = 1;
 /**
  * <code>GENERAL_STATUS_BATTERY = 2;</code>
  *
  * <pre>
  * The unit is running on battery power
  * </pre>
  */
 public static final int GENERAL_STATUS_BATTERY_VALUE = 2;
 /**
  * <code>GENERAL_STATUS_GPS_INFORMATION_AVAILABLE = 4;</code>
  *
  * <pre>
  * GPS information available
  * </pre>
  */
 public static final int GENERAL_STATUS_GPS_INFORMATION_AVAILABLE_VALUE = 4;
 /**
  * <code>GENERAL_STATUS_INPUT_OUTPUT_INFORMATION_AVAILABLE = 8;</code>
  *
  * <pre>
  * Input and output information available
  * </pre>
  */
 public static final int GENERAL_STATUS_INPUT_OUTPUT_INFORMATION_AVAILABLE_VALUE = 8;
 /**
  * <code>GENERAL_STATUS_GPS_POSITION_INVALID = 16;</code>
  *
  * <pre>
  * Specifies that the provided latitude/longitude and other GPS data was valid some time ago but is invalid now
  * </pre>
  */
 public static final int GENERAL_STATUS_GPS_POSITION_INVALID_VALUE = 16;
 /**
  * <code>GENERAL_STATUS_GPS_STATUS_VALID = 32;</code>
  *
  * <pre>
  * Specifies that GPS is in valid status
  * </pre>
  */
 public static final int GENERAL_STATUS_GPS_STATUS_VALID_VALUE = 32;
 /**
  * <code>GENERAL_STATUS_GPS_ANTENNA_CONNECTED = 64;</code>
  *
  * <pre>
  * Specifies that GPS antenna is connected
  * </pre>
  */
 public static final int GENERAL_STATUS_GPS_ANTENNA_CONNECTED_VALUE = 64;


 public final int getNumber() { return value; }

 public static GeneralStatusType valueOf(int value) {
   switch (value) {
     case 1: return GENERAL_STATUS_IGNITION;
     case 2: return GENERAL_STATUS_BATTERY;
     case 4: return GENERAL_STATUS_GPS_INFORMATION_AVAILABLE;
     case 8: return GENERAL_STATUS_INPUT_OUTPUT_INFORMATION_AVAILABLE;
     case 16: return GENERAL_STATUS_GPS_POSITION_INVALID;
     case 32: return GENERAL_STATUS_GPS_STATUS_VALID;
     case 64: return GENERAL_STATUS_GPS_ANTENNA_CONNECTED;
     default: return null;
   }
 }

 public static com.google.protobuf.Internal.EnumLiteMap<GeneralStatusType>
     internalGetValueMap() {
   return internalValueMap;
 }
 private static com.google.protobuf.Internal.EnumLiteMap<GeneralStatusType>
     internalValueMap =
       new com.google.protobuf.Internal.EnumLiteMap<GeneralStatusType>() {
         public GeneralStatusType findValueByNumber(int number) {
           return GeneralStatusType.valueOf(number);
         }
       };

 public final com.google.protobuf.Descriptors.EnumValueDescriptor
     getValueDescriptor() {
   return getDescriptor().getValues().get(index);
 }
 public final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptorForType() {
   return getDescriptor();
 }
 public static final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptor() {
   return GeneralStatusTypeProto.getDescriptor().getEnumTypes().get(0);
 }

 private static final GeneralStatusType[] VALUES = values();

 public static GeneralStatusType valueOf(
     com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
   if (desc.getType() != getDescriptor()) {
     throw new java.lang.IllegalArgumentException(
       "EnumValueDescriptor is not for this type.");
   }
   return VALUES[desc.getIndex()];
 }

 private final int index;
 private final int value;

 private GeneralStatusType(int index, int value) {
   this.index = index;
   this.value = value;
 }

 // @@protoc_insertion_point(enum_scope:GeneralStatusType)
}


public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\034GeneralStatusTypeProto.proto*\251\002\n\021Gener" +
   "alStatusType\022\033\n\027GENERAL_STATUS_IGNITION\020" +
   "\001\022\032\n\026GENERAL_STATUS_BATTERY\020\002\022,\n(GENERAL" +
   "_STATUS_GPS_INFORMATION_AVAILABLE\020\004\0225\n1G" +
   "ENERAL_STATUS_INPUT_OUTPUT_INFORMATION_A" +
   "VAILABLE\020\010\022\'\n#GENERAL_STATUS_GPS_POSITIO" +
   "N_INVALID\020\020\022#\n\037GENERAL_STATUS_GPS_STATUS" +
   "_VALID\020 \022(\n$GENERAL_STATUS_GPS_ANTENNA_C" +
   "ONNECTED\020@"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
     }, assigner);
}

// @@protoc_insertion_point(outer_class_scope)
}

