package scopeProto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: TripSummaryProto.proto

public final class TripSummaryProto {
private TripSummaryProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
public interface TripSummaryOrBuilder extends
   // @@protoc_insertion_point(interface_extends:TripSummary)
   com.google.protobuf.MessageOrBuilder {

 /**
  * <code>required .EventHeader header = 1;</code>
  */
 boolean hasHeader();
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 EventHeaderProto.EventHeader getHeader();
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder();

 /**
  * <code>optional double latitude_start = 2;</code>
  *
  * <pre>
  * Latitude start (-90...90) in degrees. Accuracy: 0.0000001
  * </pre>
  */
 boolean hasLatitudeStart();
 /**
  * <code>optional double latitude_start = 2;</code>
  *
  * <pre>
  * Latitude start (-90...90) in degrees. Accuracy: 0.0000001
  * </pre>
  */
 double getLatitudeStart();

 /**
  * <code>optional double longitude_start = 3;</code>
  *
  * <pre>
  * Longitude start (-180...180) in degrees. Accuracy: 0.0000001
  * </pre>
  */
 boolean hasLongitudeStart();
 /**
  * <code>optional double longitude_start = 3;</code>
  *
  * <pre>
  * Longitude start (-180...180) in degrees. Accuracy: 0.0000001
  * </pre>
  */
 double getLongitudeStart();

 /**
  * <code>optional uint32 trip_duration = 4;</code>
  *
  * <pre>
  * Trip duration in seconds
  * </pre>
  */
 boolean hasTripDuration();
 /**
  * <code>optional uint32 trip_duration = 4;</code>
  *
  * <pre>
  * Trip duration in seconds
  * </pre>
  */
 int getTripDuration();

 /**
  * <code>optional uint32 trip_distance = 5;</code>
  *
  * <pre>
  * Trip distance in meters
  * </pre>
  */
 boolean hasTripDistance();
 /**
  * <code>optional uint32 trip_distance = 5;</code>
  *
  * <pre>
  * Trip distance in meters
  * </pre>
  */
 int getTripDistance();

 /**
  * <code>optional uint32 trip_max_speed = 6;</code>
  *
  * <pre>
  * Trip maximum speed (km/h)
  * </pre>
  */
 boolean hasTripMaxSpeed();
 /**
  * <code>optional uint32 trip_max_speed = 6;</code>
  *
  * <pre>
  * Trip maximum speed (km/h)
  * </pre>
  */
 int getTripMaxSpeed();

 /**
  * <code>optional uint32 gprs_status_start = 7;</code>
  *
  * <pre>
  * GPRS status start (0..255)
  * </pre>
  */
 boolean hasGprsStatusStart();
 /**
  * <code>optional uint32 gprs_status_start = 7;</code>
  *
  * <pre>
  * GPRS status start (0..255)
  * </pre>
  */
 int getGprsStatusStart();
}
/**
* Protobuf type {@code TripSummary}
*
* <pre>
* Trip Summary
* </pre>
*/
public static final class TripSummary extends
   com.google.protobuf.GeneratedMessage implements
   // @@protoc_insertion_point(message_implements:TripSummary)
   TripSummaryOrBuilder {
 // Use TripSummary.newBuilder() to construct.
 private TripSummary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
   super(builder);
   this.unknownFields = builder.getUnknownFields();
 }
 private TripSummary(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

 private static final TripSummary defaultInstance;
 public static TripSummary getDefaultInstance() {
   return defaultInstance;
 }

 public TripSummary getDefaultInstanceForType() {
   return defaultInstance;
 }

 private final com.google.protobuf.UnknownFieldSet unknownFields;
 @java.lang.Override
 public final com.google.protobuf.UnknownFieldSet
     getUnknownFields() {
   return this.unknownFields;
 }
 private TripSummary(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   initFields();
   int mutable_bitField0_ = 0;
   com.google.protobuf.UnknownFieldSet.Builder unknownFields =
       com.google.protobuf.UnknownFieldSet.newBuilder();
   try {
     boolean done = false;
     while (!done) {
       int tag = input.readTag();
       switch (tag) {
         case 0:
           done = true;
           break;
         default: {
           if (!parseUnknownField(input, unknownFields,
                                  extensionRegistry, tag)) {
             done = true;
           }
           break;
         }
         case 10: {
           EventHeaderProto.EventHeader.Builder subBuilder = null;
           if (((bitField0_ & 0x00000001) == 0x00000001)) {
             subBuilder = header_.toBuilder();
           }
           header_ = input.readMessage(EventHeaderProto.EventHeader.PARSER, extensionRegistry);
           if (subBuilder != null) {
             subBuilder.mergeFrom(header_);
             header_ = subBuilder.buildPartial();
           }
           bitField0_ |= 0x00000001;
           break;
         }
         case 17: {
           bitField0_ |= 0x00000002;
           latitudeStart_ = input.readDouble();
           break;
         }
         case 25: {
           bitField0_ |= 0x00000004;
           longitudeStart_ = input.readDouble();
           break;
         }
         case 32: {
           bitField0_ |= 0x00000008;
           tripDuration_ = input.readUInt32();
           break;
         }
         case 40: {
           bitField0_ |= 0x00000010;
           tripDistance_ = input.readUInt32();
           break;
         }
         case 48: {
           bitField0_ |= 0x00000020;
           tripMaxSpeed_ = input.readUInt32();
           break;
         }
         case 56: {
           bitField0_ |= 0x00000040;
           gprsStatusStart_ = input.readUInt32();
           break;
         }
       }
     }
   } catch (com.google.protobuf.InvalidProtocolBufferException e) {
     throw e.setUnfinishedMessage(this);
   } catch (java.io.IOException e) {
     throw new com.google.protobuf.InvalidProtocolBufferException(
         e.getMessage()).setUnfinishedMessage(this);
   } finally {
     this.unknownFields = unknownFields.build();
     makeExtensionsImmutable();
   }
 }
 public static final com.google.protobuf.Descriptors.Descriptor
     getDescriptor() {
   return TripSummaryProto.internal_static_TripSummary_descriptor;
 }

 protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
     internalGetFieldAccessorTable() {
   return TripSummaryProto.internal_static_TripSummary_fieldAccessorTable
       .ensureFieldAccessorsInitialized(
           TripSummaryProto.TripSummary.class, TripSummaryProto.TripSummary.Builder.class);
 }

 public static com.google.protobuf.Parser<TripSummary> PARSER =
     new com.google.protobuf.AbstractParser<TripSummary>() {
   public TripSummary parsePartialFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return new TripSummary(input, extensionRegistry);
   }
 };

 @java.lang.Override
 public com.google.protobuf.Parser<TripSummary> getParserForType() {
   return PARSER;
 }

 private int bitField0_;
 public static final int HEADER_FIELD_NUMBER = 1;
 private EventHeaderProto.EventHeader header_;
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public boolean hasHeader() {
   return ((bitField0_ & 0x00000001) == 0x00000001);
 }
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public EventHeaderProto.EventHeader getHeader() {
   return header_;
 }
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
   return header_;
 }

 public static final int LATITUDE_START_FIELD_NUMBER = 2;
 private double latitudeStart_;
 /**
  * <code>optional double latitude_start = 2;</code>
  *
  * <pre>
  * Latitude start (-90...90) in degrees. Accuracy: 0.0000001
  * </pre>
  */
 public boolean hasLatitudeStart() {
   return ((bitField0_ & 0x00000002) == 0x00000002);
 }
 /**
  * <code>optional double latitude_start = 2;</code>
  *
  * <pre>
  * Latitude start (-90...90) in degrees. Accuracy: 0.0000001
  * </pre>
  */
 public double getLatitudeStart() {
   return latitudeStart_;
 }

 public static final int LONGITUDE_START_FIELD_NUMBER = 3;
 private double longitudeStart_;
 /**
  * <code>optional double longitude_start = 3;</code>
  *
  * <pre>
  * Longitude start (-180...180) in degrees. Accuracy: 0.0000001
  * </pre>
  */
 public boolean hasLongitudeStart() {
   return ((bitField0_ & 0x00000004) == 0x00000004);
 }
 /**
  * <code>optional double longitude_start = 3;</code>
  *
  * <pre>
  * Longitude start (-180...180) in degrees. Accuracy: 0.0000001
  * </pre>
  */
 public double getLongitudeStart() {
   return longitudeStart_;
 }

 public static final int TRIP_DURATION_FIELD_NUMBER = 4;
 private int tripDuration_;
 /**
  * <code>optional uint32 trip_duration = 4;</code>
  *
  * <pre>
  * Trip duration in seconds
  * </pre>
  */
 public boolean hasTripDuration() {
   return ((bitField0_ & 0x00000008) == 0x00000008);
 }
 /**
  * <code>optional uint32 trip_duration = 4;</code>
  *
  * <pre>
  * Trip duration in seconds
  * </pre>
  */
 public int getTripDuration() {
   return tripDuration_;
 }

 public static final int TRIP_DISTANCE_FIELD_NUMBER = 5;
 private int tripDistance_;
 /**
  * <code>optional uint32 trip_distance = 5;</code>
  *
  * <pre>
  * Trip distance in meters
  * </pre>
  */
 public boolean hasTripDistance() {
   return ((bitField0_ & 0x00000010) == 0x00000010);
 }
 /**
  * <code>optional uint32 trip_distance = 5;</code>
  *
  * <pre>
  * Trip distance in meters
  * </pre>
  */
 public int getTripDistance() {
   return tripDistance_;
 }

 public static final int TRIP_MAX_SPEED_FIELD_NUMBER = 6;
 private int tripMaxSpeed_;
 /**
  * <code>optional uint32 trip_max_speed = 6;</code>
  *
  * <pre>
  * Trip maximum speed (km/h)
  * </pre>
  */
 public boolean hasTripMaxSpeed() {
   return ((bitField0_ & 0x00000020) == 0x00000020);
 }
 /**
  * <code>optional uint32 trip_max_speed = 6;</code>
  *
  * <pre>
  * Trip maximum speed (km/h)
  * </pre>
  */
 public int getTripMaxSpeed() {
   return tripMaxSpeed_;
 }

 public static final int GPRS_STATUS_START_FIELD_NUMBER = 7;
 private int gprsStatusStart_;
 /**
  * <code>optional uint32 gprs_status_start = 7;</code>
  *
  * <pre>
  * GPRS status start (0..255)
  * </pre>
  */
 public boolean hasGprsStatusStart() {
   return ((bitField0_ & 0x00000040) == 0x00000040);
 }
 /**
  * <code>optional uint32 gprs_status_start = 7;</code>
  *
  * <pre>
  * GPRS status start (0..255)
  * </pre>
  */
 public int getGprsStatusStart() {
   return gprsStatusStart_;
 }

 private void initFields() {
   header_ = EventHeaderProto.EventHeader.getDefaultInstance();
   latitudeStart_ = 0D;
   longitudeStart_ = 0D;
   tripDuration_ = 0;
   tripDistance_ = 0;
   tripMaxSpeed_ = 0;
   gprsStatusStart_ = 0;
 }
 private byte memoizedIsInitialized = -1;
 public final boolean isInitialized() {
   byte isInitialized = memoizedIsInitialized;
   if (isInitialized == 1) return true;
   if (isInitialized == 0) return false;

   if (!hasHeader()) {
     memoizedIsInitialized = 0;
     return false;
   }
   if (!getHeader().isInitialized()) {
     memoizedIsInitialized = 0;
     return false;
   }
   memoizedIsInitialized = 1;
   return true;
 }

 public void writeTo(com.google.protobuf.CodedOutputStream output)
                     throws java.io.IOException {
   getSerializedSize();
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     output.writeMessage(1, header_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     output.writeDouble(2, latitudeStart_);
   }
   if (((bitField0_ & 0x00000004) == 0x00000004)) {
     output.writeDouble(3, longitudeStart_);
   }
   if (((bitField0_ & 0x00000008) == 0x00000008)) {
     output.writeUInt32(4, tripDuration_);
   }
   if (((bitField0_ & 0x00000010) == 0x00000010)) {
     output.writeUInt32(5, tripDistance_);
   }
   if (((bitField0_ & 0x00000020) == 0x00000020)) {
     output.writeUInt32(6, tripMaxSpeed_);
   }
   if (((bitField0_ & 0x00000040) == 0x00000040)) {
     output.writeUInt32(7, gprsStatusStart_);
   }
   getUnknownFields().writeTo(output);
 }

 private int memoizedSerializedSize = -1;
 public int getSerializedSize() {
   int size = memoizedSerializedSize;
   if (size != -1) return size;

   size = 0;
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     size += com.google.protobuf.CodedOutputStream
       .computeMessageSize(1, header_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     size += com.google.protobuf.CodedOutputStream
       .computeDoubleSize(2, latitudeStart_);
   }
   if (((bitField0_ & 0x00000004) == 0x00000004)) {
     size += com.google.protobuf.CodedOutputStream
       .computeDoubleSize(3, longitudeStart_);
   }
   if (((bitField0_ & 0x00000008) == 0x00000008)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(4, tripDuration_);
   }
   if (((bitField0_ & 0x00000010) == 0x00000010)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(5, tripDistance_);
   }
   if (((bitField0_ & 0x00000020) == 0x00000020)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(6, tripMaxSpeed_);
   }
   if (((bitField0_ & 0x00000040) == 0x00000040)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(7, gprsStatusStart_);
   }
   size += getUnknownFields().getSerializedSize();
   memoizedSerializedSize = size;
   return size;
 }

 private static final long serialVersionUID = 0L;
 @java.lang.Override
 protected java.lang.Object writeReplace()
     throws java.io.ObjectStreamException {
   return super.writeReplace();
 }

 public static TripSummaryProto.TripSummary parseFrom(
     com.google.protobuf.ByteString data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static TripSummaryProto.TripSummary parseFrom(
     com.google.protobuf.ByteString data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static TripSummaryProto.TripSummary parseFrom(byte[] data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static TripSummaryProto.TripSummary parseFrom(
     byte[] data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static TripSummaryProto.TripSummary parseFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static TripSummaryProto.TripSummary parseFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }
 public static TripSummaryProto.TripSummary parseDelimitedFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input);
 }
 public static TripSummaryProto.TripSummary parseDelimitedFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input, extensionRegistry);
 }
 public static TripSummaryProto.TripSummary parseFrom(
     com.google.protobuf.CodedInputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static TripSummaryProto.TripSummary parseFrom(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }

 public static Builder newBuilder() { return Builder.create(); }
 public Builder newBuilderForType() { return newBuilder(); }
 public static Builder newBuilder(TripSummaryProto.TripSummary prototype) {
   return newBuilder().mergeFrom(prototype);
 }
 public Builder toBuilder() { return newBuilder(this); }

 @java.lang.Override
 protected Builder newBuilderForType(
     com.google.protobuf.GeneratedMessage.BuilderParent parent) {
   Builder builder = new Builder(parent);
   return builder;
 }
 /**
  * Protobuf type {@code TripSummary}
  *
  * <pre>
  * Trip Summary
  * </pre>
  */
 public static final class Builder extends
     com.google.protobuf.GeneratedMessage.Builder<Builder> implements
     // @@protoc_insertion_point(builder_implements:TripSummary)
     TripSummaryProto.TripSummaryOrBuilder {
   public static final com.google.protobuf.Descriptors.Descriptor
       getDescriptor() {
     return TripSummaryProto.internal_static_TripSummary_descriptor;
   }

   protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
       internalGetFieldAccessorTable() {
     return TripSummaryProto.internal_static_TripSummary_fieldAccessorTable
         .ensureFieldAccessorsInitialized(
             TripSummaryProto.TripSummary.class, TripSummaryProto.TripSummary.Builder.class);
   }

   // Construct using TripSummaryProto.TripSummary.newBuilder()
   private Builder() {
     maybeForceBuilderInitialization();
   }

   private Builder(
       com.google.protobuf.GeneratedMessage.BuilderParent parent) {
     super(parent);
     maybeForceBuilderInitialization();
   }
   private void maybeForceBuilderInitialization() {
     if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
       getHeaderFieldBuilder();
     }
   }
   private static Builder create() {
     return new Builder();
   }

   public Builder clear() {
     super.clear();
     if (headerBuilder_ == null) {
       header_ = EventHeaderProto.EventHeader.getDefaultInstance();
     } else {
       headerBuilder_.clear();
     }
     bitField0_ = (bitField0_ & ~0x00000001);
     latitudeStart_ = 0D;
     bitField0_ = (bitField0_ & ~0x00000002);
     longitudeStart_ = 0D;
     bitField0_ = (bitField0_ & ~0x00000004);
     tripDuration_ = 0;
     bitField0_ = (bitField0_ & ~0x00000008);
     tripDistance_ = 0;
     bitField0_ = (bitField0_ & ~0x00000010);
     tripMaxSpeed_ = 0;
     bitField0_ = (bitField0_ & ~0x00000020);
     gprsStatusStart_ = 0;
     bitField0_ = (bitField0_ & ~0x00000040);
     return this;
   }

   public Builder clone() {
     return create().mergeFrom(buildPartial());
   }

   public com.google.protobuf.Descriptors.Descriptor
       getDescriptorForType() {
     return TripSummaryProto.internal_static_TripSummary_descriptor;
   }

   public TripSummaryProto.TripSummary getDefaultInstanceForType() {
     return TripSummaryProto.TripSummary.getDefaultInstance();
   }

   public TripSummaryProto.TripSummary build() {
     TripSummaryProto.TripSummary result = buildPartial();
     if (!result.isInitialized()) {
       throw newUninitializedMessageException(result);
     }
     return result;
   }

   public TripSummaryProto.TripSummary buildPartial() {
     TripSummaryProto.TripSummary result = new TripSummaryProto.TripSummary(this);
     int from_bitField0_ = bitField0_;
     int to_bitField0_ = 0;
     if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
       to_bitField0_ |= 0x00000001;
     }
     if (headerBuilder_ == null) {
       result.header_ = header_;
     } else {
       result.header_ = headerBuilder_.build();
     }
     if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
       to_bitField0_ |= 0x00000002;
     }
     result.latitudeStart_ = latitudeStart_;
     if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
       to_bitField0_ |= 0x00000004;
     }
     result.longitudeStart_ = longitudeStart_;
     if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
       to_bitField0_ |= 0x00000008;
     }
     result.tripDuration_ = tripDuration_;
     if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
       to_bitField0_ |= 0x00000010;
     }
     result.tripDistance_ = tripDistance_;
     if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
       to_bitField0_ |= 0x00000020;
     }
     result.tripMaxSpeed_ = tripMaxSpeed_;
     if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
       to_bitField0_ |= 0x00000040;
     }
     result.gprsStatusStart_ = gprsStatusStart_;
     result.bitField0_ = to_bitField0_;
     onBuilt();
     return result;
   }

   public Builder mergeFrom(com.google.protobuf.Message other) {
     if (other instanceof TripSummaryProto.TripSummary) {
       return mergeFrom((TripSummaryProto.TripSummary)other);
     } else {
       super.mergeFrom(other);
       return this;
     }
   }

   public Builder mergeFrom(TripSummaryProto.TripSummary other) {
     if (other == TripSummaryProto.TripSummary.getDefaultInstance()) return this;
     if (other.hasHeader()) {
       mergeHeader(other.getHeader());
     }
     if (other.hasLatitudeStart()) {
       setLatitudeStart(other.getLatitudeStart());
     }
     if (other.hasLongitudeStart()) {
       setLongitudeStart(other.getLongitudeStart());
     }
     if (other.hasTripDuration()) {
       setTripDuration(other.getTripDuration());
     }
     if (other.hasTripDistance()) {
       setTripDistance(other.getTripDistance());
     }
     if (other.hasTripMaxSpeed()) {
       setTripMaxSpeed(other.getTripMaxSpeed());
     }
     if (other.hasGprsStatusStart()) {
       setGprsStatusStart(other.getGprsStatusStart());
     }
     this.mergeUnknownFields(other.getUnknownFields());
     return this;
   }

   public final boolean isInitialized() {
     if (!hasHeader()) {
       
       return false;
     }
     if (!getHeader().isInitialized()) {
       
       return false;
     }
     return true;
   }

   public Builder mergeFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     TripSummaryProto.TripSummary parsedMessage = null;
     try {
       parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
     } catch (com.google.protobuf.InvalidProtocolBufferException e) {
       parsedMessage = (TripSummaryProto.TripSummary) e.getUnfinishedMessage();
       throw e;
     } finally {
       if (parsedMessage != null) {
         mergeFrom(parsedMessage);
       }
     }
     return this;
   }
   private int bitField0_;

   private EventHeaderProto.EventHeader header_ = EventHeaderProto.EventHeader.getDefaultInstance();
   private com.google.protobuf.SingleFieldBuilder<
       EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder> headerBuilder_;
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public boolean hasHeader() {
     return ((bitField0_ & 0x00000001) == 0x00000001);
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeader getHeader() {
     if (headerBuilder_ == null) {
       return header_;
     } else {
       return headerBuilder_.getMessage();
     }
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder setHeader(EventHeaderProto.EventHeader value) {
     if (headerBuilder_ == null) {
       if (value == null) {
         throw new NullPointerException();
       }
       header_ = value;
       onChanged();
     } else {
       headerBuilder_.setMessage(value);
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder setHeader(
       EventHeaderProto.EventHeader.Builder builderForValue) {
     if (headerBuilder_ == null) {
       header_ = builderForValue.build();
       onChanged();
     } else {
       headerBuilder_.setMessage(builderForValue.build());
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder mergeHeader(EventHeaderProto.EventHeader value) {
     if (headerBuilder_ == null) {
       if (((bitField0_ & 0x00000001) == 0x00000001) &&
           header_ != EventHeaderProto.EventHeader.getDefaultInstance()) {
         header_ =
           EventHeaderProto.EventHeader.newBuilder(header_).mergeFrom(value).buildPartial();
       } else {
         header_ = value;
       }
       onChanged();
     } else {
       headerBuilder_.mergeFrom(value);
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder clearHeader() {
     if (headerBuilder_ == null) {
       header_ = EventHeaderProto.EventHeader.getDefaultInstance();
       onChanged();
     } else {
       headerBuilder_.clear();
     }
     bitField0_ = (bitField0_ & ~0x00000001);
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeader.Builder getHeaderBuilder() {
     bitField0_ |= 0x00000001;
     onChanged();
     return getHeaderFieldBuilder().getBuilder();
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
     if (headerBuilder_ != null) {
       return headerBuilder_.getMessageOrBuilder();
     } else {
       return header_;
     }
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   private com.google.protobuf.SingleFieldBuilder<
       EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder> 
       getHeaderFieldBuilder() {
     if (headerBuilder_ == null) {
       headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
           EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder>(
               getHeader(),
               getParentForChildren(),
               isClean());
       header_ = null;
     }
     return headerBuilder_;
   }

   private double latitudeStart_ ;
   /**
    * <code>optional double latitude_start = 2;</code>
    *
    * <pre>
    * Latitude start (-90...90) in degrees. Accuracy: 0.0000001
    * </pre>
    */
   public boolean hasLatitudeStart() {
     return ((bitField0_ & 0x00000002) == 0x00000002);
   }
   /**
    * <code>optional double latitude_start = 2;</code>
    *
    * <pre>
    * Latitude start (-90...90) in degrees. Accuracy: 0.0000001
    * </pre>
    */
   public double getLatitudeStart() {
     return latitudeStart_;
   }
   /**
    * <code>optional double latitude_start = 2;</code>
    *
    * <pre>
    * Latitude start (-90...90) in degrees. Accuracy: 0.0000001
    * </pre>
    */
   public Builder setLatitudeStart(double value) {
     bitField0_ |= 0x00000002;
     latitudeStart_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional double latitude_start = 2;</code>
    *
    * <pre>
    * Latitude start (-90...90) in degrees. Accuracy: 0.0000001
    * </pre>
    */
   public Builder clearLatitudeStart() {
     bitField0_ = (bitField0_ & ~0x00000002);
     latitudeStart_ = 0D;
     onChanged();
     return this;
   }

   private double longitudeStart_ ;
   /**
    * <code>optional double longitude_start = 3;</code>
    *
    * <pre>
    * Longitude start (-180...180) in degrees. Accuracy: 0.0000001
    * </pre>
    */
   public boolean hasLongitudeStart() {
     return ((bitField0_ & 0x00000004) == 0x00000004);
   }
   /**
    * <code>optional double longitude_start = 3;</code>
    *
    * <pre>
    * Longitude start (-180...180) in degrees. Accuracy: 0.0000001
    * </pre>
    */
   public double getLongitudeStart() {
     return longitudeStart_;
   }
   /**
    * <code>optional double longitude_start = 3;</code>
    *
    * <pre>
    * Longitude start (-180...180) in degrees. Accuracy: 0.0000001
    * </pre>
    */
   public Builder setLongitudeStart(double value) {
     bitField0_ |= 0x00000004;
     longitudeStart_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional double longitude_start = 3;</code>
    *
    * <pre>
    * Longitude start (-180...180) in degrees. Accuracy: 0.0000001
    * </pre>
    */
   public Builder clearLongitudeStart() {
     bitField0_ = (bitField0_ & ~0x00000004);
     longitudeStart_ = 0D;
     onChanged();
     return this;
   }

   private int tripDuration_ ;
   /**
    * <code>optional uint32 trip_duration = 4;</code>
    *
    * <pre>
    * Trip duration in seconds
    * </pre>
    */
   public boolean hasTripDuration() {
     return ((bitField0_ & 0x00000008) == 0x00000008);
   }
   /**
    * <code>optional uint32 trip_duration = 4;</code>
    *
    * <pre>
    * Trip duration in seconds
    * </pre>
    */
   public int getTripDuration() {
     return tripDuration_;
   }
   /**
    * <code>optional uint32 trip_duration = 4;</code>
    *
    * <pre>
    * Trip duration in seconds
    * </pre>
    */
   public Builder setTripDuration(int value) {
     bitField0_ |= 0x00000008;
     tripDuration_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 trip_duration = 4;</code>
    *
    * <pre>
    * Trip duration in seconds
    * </pre>
    */
   public Builder clearTripDuration() {
     bitField0_ = (bitField0_ & ~0x00000008);
     tripDuration_ = 0;
     onChanged();
     return this;
   }

   private int tripDistance_ ;
   /**
    * <code>optional uint32 trip_distance = 5;</code>
    *
    * <pre>
    * Trip distance in meters
    * </pre>
    */
   public boolean hasTripDistance() {
     return ((bitField0_ & 0x00000010) == 0x00000010);
   }
   /**
    * <code>optional uint32 trip_distance = 5;</code>
    *
    * <pre>
    * Trip distance in meters
    * </pre>
    */
   public int getTripDistance() {
     return tripDistance_;
   }
   /**
    * <code>optional uint32 trip_distance = 5;</code>
    *
    * <pre>
    * Trip distance in meters
    * </pre>
    */
   public Builder setTripDistance(int value) {
     bitField0_ |= 0x00000010;
     tripDistance_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 trip_distance = 5;</code>
    *
    * <pre>
    * Trip distance in meters
    * </pre>
    */
   public Builder clearTripDistance() {
     bitField0_ = (bitField0_ & ~0x00000010);
     tripDistance_ = 0;
     onChanged();
     return this;
   }

   private int tripMaxSpeed_ ;
   /**
    * <code>optional uint32 trip_max_speed = 6;</code>
    *
    * <pre>
    * Trip maximum speed (km/h)
    * </pre>
    */
   public boolean hasTripMaxSpeed() {
     return ((bitField0_ & 0x00000020) == 0x00000020);
   }
   /**
    * <code>optional uint32 trip_max_speed = 6;</code>
    *
    * <pre>
    * Trip maximum speed (km/h)
    * </pre>
    */
   public int getTripMaxSpeed() {
     return tripMaxSpeed_;
   }
   /**
    * <code>optional uint32 trip_max_speed = 6;</code>
    *
    * <pre>
    * Trip maximum speed (km/h)
    * </pre>
    */
   public Builder setTripMaxSpeed(int value) {
     bitField0_ |= 0x00000020;
     tripMaxSpeed_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 trip_max_speed = 6;</code>
    *
    * <pre>
    * Trip maximum speed (km/h)
    * </pre>
    */
   public Builder clearTripMaxSpeed() {
     bitField0_ = (bitField0_ & ~0x00000020);
     tripMaxSpeed_ = 0;
     onChanged();
     return this;
   }

   private int gprsStatusStart_ ;
   /**
    * <code>optional uint32 gprs_status_start = 7;</code>
    *
    * <pre>
    * GPRS status start (0..255)
    * </pre>
    */
   public boolean hasGprsStatusStart() {
     return ((bitField0_ & 0x00000040) == 0x00000040);
   }
   /**
    * <code>optional uint32 gprs_status_start = 7;</code>
    *
    * <pre>
    * GPRS status start (0..255)
    * </pre>
    */
   public int getGprsStatusStart() {
     return gprsStatusStart_;
   }
   /**
    * <code>optional uint32 gprs_status_start = 7;</code>
    *
    * <pre>
    * GPRS status start (0..255)
    * </pre>
    */
   public Builder setGprsStatusStart(int value) {
     bitField0_ |= 0x00000040;
     gprsStatusStart_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 gprs_status_start = 7;</code>
    *
    * <pre>
    * GPRS status start (0..255)
    * </pre>
    */
   public Builder clearGprsStatusStart() {
     bitField0_ = (bitField0_ & ~0x00000040);
     gprsStatusStart_ = 0;
     onChanged();
     return this;
   }

   // @@protoc_insertion_point(builder_scope:TripSummary)
 }

 static {
   defaultInstance = new TripSummary(true);
   defaultInstance.initFields();
 }

 // @@protoc_insertion_point(class_scope:TripSummary)
}

private static final com.google.protobuf.Descriptors.Descriptor
 internal_static_TripSummary_descriptor;
private static
 com.google.protobuf.GeneratedMessage.FieldAccessorTable
   internal_static_TripSummary_fieldAccessorTable;

public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\026TripSummaryProto.proto\032\026EventHeaderPro" +
   "to.proto\"\275\001\n\013TripSummary\022\034\n\006header\030\001 \002(\013" +
   "2\014.EventHeader\022\026\n\016latitude_start\030\002 \001(\001\022\027" +
   "\n\017longitude_start\030\003 \001(\001\022\025\n\rtrip_duration" +
   "\030\004 \001(\r\022\025\n\rtrip_distance\030\005 \001(\r\022\026\n\016trip_ma" +
   "x_speed\030\006 \001(\r\022\031\n\021gprs_status_start\030\007 \001(\r"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
       EventHeaderProto.getDescriptor(),
     }, assigner);
 internal_static_TripSummary_descriptor =
   getDescriptor().getMessageTypes().get(0);
 internal_static_TripSummary_fieldAccessorTable = new
   com.google.protobuf.GeneratedMessage.FieldAccessorTable(
     internal_static_TripSummary_descriptor,
     new java.lang.String[] { "Header", "LatitudeStart", "LongitudeStart", "TripDuration", "TripDistance", "TripMaxSpeed", "GprsStatusStart", });
 EventHeaderProto.getDescriptor();
}

// @@protoc_insertion_point(outer_class_scope)
}
